# docker compose up -d

version: "3"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodeapi-SMART-API-WebAPP
    container_name: nginx-reverse-proxy-api

  nodeapi-SMART-API-WebAPP:
    image: node:18.17.1
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    volumes:
      - ./nest01:/projects
    working_dir: /projects
    environment:
      - TZ=Asia/Bangkok
      - PGTZ=Asia/Bangkok
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    command: ["node", "/projects/dist/main.js"]
    container_name: nodeapi-SMART-API-WebAPP
